package tz.co.flex.payment.service;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tz.co.flex.payment.model.dto.AccountDto;
import tz.co.flex.payment.exception.AccountException;
import tz.co.flex.payment.model.Account;
import tz.co.flex.payment.repository.AccountRepository;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class AccountService {

    private final AccountRepository accountRepository;

    @Transactional
    public AccountDto createAccount(AccountDto accountDto) {
        // Check if account with same name already exists
        if (accountRepository.findByName((accountDto.getName())).isPresent()) {
            throw new AccountException("Account with this name already exists");
        }

        Account account = new Account();
        account.setName(accountDto.getName());
        account.setWebhookUrl(accountDto.getWebhookUrl());
        account.setAllowedIps(accountDto.getAllowedIps());
        account.setActive(accountDto.isActive());

        // The API token will be auto-generated by @PrePersist in Account entity
        Account savedAccount = accountRepository.save(account);
        
        return convertToDto(savedAccount);
    }

    @Transactional(readOnly = true)
    public AccountDto getAccount(String id) {
        Account account = accountRepository.findById(id)
            .orElseThrow(() -> new AccountException("Account not found with id: " + id));
        return convertToDto(account);
    }

    @Transactional(readOnly = true)
    public List<AccountDto> getAllAccounts() {
        return accountRepository.findAll().stream()
            .map(this::convertToDto)
            .collect(Collectors.toList());
    }

    @Transactional
    public AccountDto updateAccount(String id, AccountDto accountDto) {
        Account account = accountRepository.findById(id)
            .orElseThrow(() -> new AccountException("Account not found with id: " + id));

        // Check if name is being changed and if it's already taken
        if (!account.getName().equals(accountDto.getName()) && 
            accountRepository.findByName(accountDto.getName()).isPresent()) {
            throw new AccountException("Another account with this name already exists");
        }

        account.setName(accountDto.getName());
        account.setWebhookUrl(accountDto.getWebhookUrl());
        account.setAllowedIps(accountDto.getAllowedIps());
        account.setActive(accountDto.isActive());

        Account updatedAccount = accountRepository.save(account);
        return convertToDto(updatedAccount);
    }

    @Transactional
    public void deleteAccount(String id) {
        if (!accountRepository.existsById(id)) {
            throw new AccountException("Account not found with id: " + id);
        }
        accountRepository.deleteById(id);
    }

    @Transactional
    public String regenerateApiToken(String id) {
        Account account = accountRepository.findById(id)
            .orElseThrow(() -> new AccountException("Account not found with id: " + id));
        
        // Setting to null will trigger the @PrePersist to generate a new token
        account.setApiToken(null);
        Account updatedAccount = accountRepository.save(account);
        return updatedAccount.getApiToken();
    }

    @Transactional(readOnly = true)
    public boolean isIpAllowed(String apiToken, String ipAddress) {
        return accountRepository.findByApiToken(apiToken)
            .map(account -> {
                if (account.getAllowedIps() == null || account.getAllowedIps().trim().isEmpty()) {
                    return true; // No IP restrictions
                }
                String[] allowedIps = account.getAllowedIps().split(",");
                for (String allowedIp : allowedIps) {
                    if (allowedIp.trim().equals(ipAddress)) {
                        return true;
                    }
                }
                return false;
            })
            .orElse(false);
    }

    private AccountDto convertToDto(Account account) {
        AccountDto dto = new AccountDto();
        dto.setId(account.getId());
        dto.setName(account.getName());
        dto.setWebhookUrl(account.getWebhookUrl());
        dto.setAllowedIps(account.getAllowedIps());
        dto.setActive(account.isActive());
        dto.setApiToken(account.getApiToken());
        return dto;
    }
}
