CREATE TABLE customer_groups
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(500),
    CONSTRAINT pk_customer_groups PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE group_customers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id    BIGINT,
    customer_id BIGINT,
    CONSTRAINT pk_group_customers PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content      VARCHAR(500)                            NOT NULL,
    sender_id    BIGINT                                  NOT NULL,
    group_id     BIGINT,
    message_type SMALLINT                                NOT NULL,
    status       SMALLINT                                NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    sent_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id     VARCHAR(255)                            NOT NULL,
    customer_id        VARCHAR(255)                            NOT NULL,
    amount             DECIMAL                                 NOT NULL,
    currency           VARCHAR(3),
    status             VARCHAR(255)                            NOT NULL,
    payment_method     VARCHAR(255),
    payment_reference  VARCHAR(255),
    provider_reference VARCHAR(255),
    description        VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    completed_at       TIMESTAMP WITHOUT TIME ZONE,
    last_status_update TIMESTAMP WITHOUT TIME ZONE,
    error_message      VARCHAR(255),
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id INTEGER NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(20),
    email        VARCHAR(50),
    password     VARCHAR(120),
    full_name    VARCHAR(100),
    phone_number VARCHAR(20),
    active       BOOLEAN                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);

ALTER TABLE customer_groups
    ADD CONSTRAINT uc_customer_groups_name UNIQUE (name);

ALTER TABLE customers
    ADD CONSTRAINT uc_customers_email UNIQUE (email);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_transactionid UNIQUE (transaction_id);

ALTER TABLE group_customers
    ADD CONSTRAINT FK_GROUP_CUSTOMERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE group_customers
    ADD CONSTRAINT FK_GROUP_CUSTOMERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES customer_groups (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_GROUP FOREIGN KEY (group_id) REFERENCES customer_groups (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES users (id);